"""
Simple Class to save data/models/statistics/plots.
"""
from config.config import *
import numpy as np
import os
import joblib
import json



class StorageManager:
    def __init__(self):
        pass

    def store_predictions(self, data, prefix:str, modelspec:str):
        predictions_path = PREDICTIONS_DIR / prefix / modelspec
        np.save(predictions_path, data)
    
    def store_statistics(self):
        #store model statistics
        pass
    
    def store_figures(self):
        #store figures generated by plot
        pass